import { db, pool } from "@workspace/db";
import { inspectionsTable, warehouseReceiptsTable } from "@workspace/db/schema";

async function seed() {
  await db.delete(warehouseReceiptsTable);
  await db.delete(inspectionsTable);

  await db.insert(inspectionsTable).values([
    {
      id: "insp-001",
      intakeId: "intake-001",
      warehouseId: "wh-001",
      inspectorId: "checker-001",
      inspectionType: "intake",
      commodity: "Maize",
      variety: "White Maize",
      moisturePercent: "12.4",
      brokenGrainPercent: "1.8",
      foreignMatterPercent: "0.9",
      pestDamagePercent: "0.5",
      moldPresent: false,
      aflatoxinDetected: false,
      grade: "A",
      damageLevel: "none",
      netWeightKg: "4950",
      grossWeightKg: "5000",
      bagCount: "50",
      packagingType: "bags",
      temperatureCelsius: "22.5",
      humidityPercent: "58.0",
      storageMethod: "Elevated pallets",
      stackPosition: "Aisle 3, Stack B",
      certifications: JSON.stringify(["Export Grade", "Phytosanitary"]),
      licenseNumber: "INS-8821",
      organization: "Nairobi Grain Inspection Unit",
      riskFlags: JSON.stringify([]),
      status: "approved",
      approvedBy: "admin-001",
      inspectionDate: new Date("2026-01-15"),
    },
    {
      id: "insp-002",
      intakeId: "intake-002",
      warehouseId: "wh-002",
      inspectorId: "checker-001",
      inspectionType: "intake",
      commodity: "Coffee",
      variety: "Arabica AA",
      moisturePercent: "11.0",
      brokenGrainPercent: "0.5",
      foreignMatterPercent: "0.2",
      pestDamagePercent: "0.1",
      moldPresent: false,
      aflatoxinDetected: false,
      grade: "A",
      damageLevel: "none",
      netWeightKg: "790",
      grossWeightKg: "800",
      bagCount: "8",
      packagingType: "bags",
      temperatureCelsius: "20.0",
      humidityPercent: "52.0",
      storageMethod: "Climate-controlled",
      stackPosition: "Aisle 1, Stack A",
      certifications: JSON.stringify(["Export Grade", "Organic", "Phytosanitary"]),
      licenseNumber: "INS-8821",
      organization: "Mombasa Grain Inspection Unit",
      riskFlags: JSON.stringify([]),
      status: "approved",
      approvedBy: "admin-001",
      inspectionDate: new Date("2026-01-22"),
    },
    {
      id: "insp-003",
      intakeId: "intake-003",
      warehouseId: "wh-001",
      inspectorId: "checker-001",
      inspectionType: "intake",
      commodity: "Sorghum",
      variety: "Grade B Sorghum",
      moisturePercent: "15.8",
      brokenGrainPercent: "3.5",
      foreignMatterPercent: "2.1",
      pestDamagePercent: "1.2",
      moldPresent: false,
      aflatoxinDetected: false,
      grade: "B",
      damageLevel: "minor",
      netWeightKg: "2950",
      grossWeightKg: "3000",
      bagCount: "30",
      packagingType: "bags",
      temperatureCelsius: "25.0",
      humidityPercent: "65.0",
      storageMethod: "Standard racking",
      stackPosition: "Aisle 5, Stack C",
      certifications: JSON.stringify(["Domestic Grade"]),
      licenseNumber: "INS-8821",
      organization: "Nairobi Grain Inspection Unit",
      riskFlags: JSON.stringify(["Moisture > 14% — High Storage Risk"]),
      status: "pending",
      inspectionDate: new Date("2026-02-05"),
    },
    {
      id: "insp-004",
      intakeId: "intake-004",
      warehouseId: "wh-003",
      inspectorId: "checker-001",
      inspectionType: "intake",
      commodity: "Beans",
      variety: "Dry Beans",
      moisturePercent: "11.5",
      brokenGrainPercent: "0.8",
      foreignMatterPercent: "0.4",
      pestDamagePercent: "0.2",
      moldPresent: false,
      aflatoxinDetected: false,
      grade: "B",
      damageLevel: "none",
      netWeightKg: "495",
      grossWeightKg: "500",
      bagCount: "5",
      packagingType: "bags",
      temperatureCelsius: "21.0",
      humidityPercent: "55.0",
      storageMethod: "Standard racking",
      stackPosition: "Aisle 2, Stack A",
      certifications: JSON.stringify(["Domestic Grade"]),
      licenseNumber: "INS-9012",
      organization: "Eldoret Inspection Unit",
      riskFlags: JSON.stringify([]),
      status: "pending",
      inspectionDate: new Date("2026-02-18"),
    },
    {
      id: "insp-005",
      intakeId: "intake-005",
      warehouseId: "wh-001",
      inspectorId: "checker-001",
      inspectionType: "collateral_verification",
      commodity: "Wheat",
      variety: "Hard Red Wheat",
      moisturePercent: "16.2",
      brokenGrainPercent: "4.2",
      foreignMatterPercent: "3.8",
      pestDamagePercent: "3.1",
      moldPresent: true,
      aflatoxinDetected: false,
      grade: "C",
      damageLevel: "moderate",
      netWeightKg: "990",
      grossWeightKg: "1000",
      bagCount: "10",
      packagingType: "bags",
      temperatureCelsius: "28.0",
      humidityPercent: "72.0",
      storageMethod: "Ground floor",
      stackPosition: "Aisle 7, Stack D",
      certifications: JSON.stringify([]),
      licenseNumber: "INS-8821",
      organization: "Nairobi Grain Inspection Unit",
      riskFlags: JSON.stringify([
        "Moisture > 14% — High Storage Risk",
        "Foreign Matter > 3% — Downgrade Required",
        "Pest Damage > 2% — Fumigation Required",
      ]),
      status: "rejected",
      inspectionDate: new Date("2026-03-01"),
    },
  ]);

  await db.insert(warehouseReceiptsTable).values([
    {
      id: "wr-001",
      receiptNumber: "WR-2026-0001",
      registryRefId: "WRSC-KE-2026-001",
      intakeId: "intake-001",
      inspectionId: "insp-001",
      warehouseId: "wh-001",
      ownerId: "farmer-001",
      organizationName: "Trans Nzoia Farmers Cooperative",
      commodity: "Maize",
      grade: "A",
      quantityKg: "5000",
      packagingType: "bags",
      storageLocation: "Block A",
      stackPosition: "Aisle 3, Stack B",
      inspectionDate: new Date("2026-01-15"),
      dateIssued: new Date("2026-01-16"),
      expiryDate: new Date("2026-04-16"),
      reInspectionDate: new Date("2026-03-16"),
      status: "collateral_locked",
      tokenId: "TH-WR-0042",
      warehouseOperatorSignature: "SIG-WH-1737033600000",
      inspectionAuthoritySignature: "SIG-INS-1737033600001",
      registrySignature: "SIG-REG-1737033600002",
      notes: "Grade A Maize, export quality. Collateral locked for loan LN-2026-001.",
    },
    {
      id: "wr-002",
      receiptNumber: "WR-2026-0002",
      registryRefId: "WRSC-KE-2026-002",
      intakeId: "intake-002",
      inspectionId: "insp-002",
      warehouseId: "wh-002",
      ownerId: "farmer-002",
      organizationName: null,
      commodity: "Coffee",
      grade: "A",
      quantityKg: "800",
      packagingType: "bags",
      storageLocation: "Climate Block C1",
      stackPosition: "Aisle 1, Stack A",
      inspectionDate: new Date("2026-01-22"),
      dateIssued: new Date("2026-01-23"),
      expiryDate: new Date("2026-04-23"),
      reInspectionDate: new Date("2026-03-23"),
      status: "active",
      tokenId: "TH-WR-0043",
      warehouseOperatorSignature: "SIG-WH-1737033700000",
      inspectionAuthoritySignature: "SIG-INS-1737033700001",
      registrySignature: "SIG-REG-1737033700002",
      notes: "Arabica AA, organic certified. Available for trade or loan.",
    },
    {
      id: "wr-003",
      receiptNumber: "WR-2026-0003",
      registryRefId: null,
      intakeId: "intake-003",
      inspectionId: "insp-003",
      warehouseId: "wh-001",
      ownerId: "farmer-002",
      organizationName: null,
      commodity: "Sorghum",
      grade: "B",
      quantityKg: "3000",
      packagingType: "bags",
      storageLocation: "Block B",
      stackPosition: "Aisle 5, Stack C",
      inspectionDate: new Date("2026-02-05"),
      dateIssued: new Date("2026-02-06"),
      expiryDate: new Date("2026-05-06"),
      reInspectionDate: new Date("2026-04-06"),
      status: "draft",
      tokenId: null,
      warehouseOperatorSignature: null,
      inspectionAuthoritySignature: null,
      registrySignature: null,
      notes: "Moisture risk flagged — awaiting re-inspection before activation.",
    },
    {
      id: "wr-004",
      receiptNumber: "WR-2025-0088",
      registryRefId: "WRSC-KE-2025-088",
      intakeId: null,
      inspectionId: null,
      warehouseId: "wh-003",
      ownerId: "farmer-003",
      organizationName: "Uasin Gishu Farmers Ltd",
      commodity: "Wheat",
      grade: "B",
      quantityKg: "12000",
      packagingType: "bulk",
      storageLocation: "Silo 2",
      stackPosition: null,
      inspectionDate: new Date("2025-11-10"),
      dateIssued: new Date("2025-11-11"),
      expiryDate: new Date("2026-02-11"),
      reInspectionDate: new Date("2026-01-11"),
      status: "expired",
      tokenId: "TH-WR-0031",
      warehouseOperatorSignature: "SIG-WH-1731283200000",
      inspectionAuthoritySignature: "SIG-INS-1731283200001",
      registrySignature: "SIG-REG-1731283200002",
      notes: "Expired — renewal required before further use.",
    },
  ]);

  console.log("Seeded 5 inspections and 4 warehouse receipts");
  await pool.end();
}

seed().catch((e) => { console.error(e); process.exit(1); });
